# Generated by Django 3.2 on 2021-04-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customers')),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels')),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Queen', 'Queen'), ('King', 'King')], max_length=50)),
                ('room_code', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='rooms')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('view_count', models.BigIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hbsapp.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='payment_methods')),
                ('test_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('live_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('test_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('live_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=50, null=True)),
                ('return_url', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_request_url', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_verify_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_persons', models.PositiveIntegerField(default=1)),
                ('booking_starts', models.DateField()),
                ('booking_ends', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], max_length=50)),
                ('status_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_checked_in', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(5, 'One of the best room, I highly recommend to stay here'), (4, 'Very Good Room, I recommend to stay here'), (3, 'Good Room and nice service'), (2, 'Its ok, no comment'), (1, 'I do not recommend this room')], default=5)),
                ('amount', models.PositiveIntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hbsapp.customer')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hbsapp.hotelroom')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hbsapp.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
