# Generated by Django 3.2 on 2021-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbsapp', '0002_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
