# Generated by Django 3.2 on 2021-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbsapp', '0005_remove_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='marked_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='maximum_capacity',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2),
        ),
    ]
